### ISSUE TITLE
How to get datasets mentioned in paper？

### ISSUE THREAD

**Issue by liyiersan** [hust-linyi/Multimodal-Medical-Image-Synthesis#1]
Sir, there are two datasets mentioned in paper. Prostate Multi-Parametric Magnetic Resonance Imaging Dataset and IXI T1w-T2w Brain Dataset. As for the Prostate Multi-Parametric Magnetic Resonance Imaging Dataset, could you please show me how to get the "locally collected dataset including 156 patients data pathologically validated by a 12-core systematic TRUS-guided plus targeted prostate biopsy"? I'll appreciate it very much if you could help me. Thanks , thanks, thanks. Best wishes to you.

**Comment by hust-linyi** [comment]
I'd like to apology that I missed this issue...
Although I know that you must have figured out the solution and moved on to other projects, I want to clarify that the IXI T1w-T2w Brain dataset is available [here](https://brain-development.org/ixi-dataset/). The Prostate Multi-Parametric MRI dataset is collected locally, and we can't not release it due to the concern of patients's privacy.
